---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: fedexapp
 labels:
  app: fedexapp
spec:
 replicas: 1
 selector:
  matchLabels:
   app: fedexapp
 template:
  metadata: 
   labels:
    app: fedexapp
  spec:
   containers:
   - name: fedexapp
     image: shrikant7t/devops:tagversion
     ports:
     - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: fedexapp
spec:
  type: LoadBalancer
  selector:
    app: fedexapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
